### ISSUE TITLE
노래퀴즈. 못 맞추면 이따가 고기사야됨.

### ISSUE THREAD

**Issue by hojak99** [Nuwanda22/IPConfigurator#3]
이 노래를 부른 그룹은 2명입니다. 원래 따로 그룹이 있었으나 그 그룹에서 2명이 나와서 부른 노래입니다. 이 그룹은 방송에서 왜 그룹명이 이거냐고 질문 받았던 적이 있습니다.  

2013년 곡이며 티저 뮤비는 2012년에 나왔습니다.

ㅇㄺ ㅅㄱ ㅇㅂㅎ ㅈ ㅁㄹㅇ ㄴㅁㅇ ㅁㅊㅈ ㅇㅇ ㄴ ㅇㅅㅇ ㅊㅅㅇ ㅇㄷ ㅇㄷ ㄴ ㅈㅎ ㅎㄱㄱ ㅇㄷ ㅇㄷ ㄴ ㅅㅀㄷㄱ ㅁㅎㄱ ㅅㅇㄷ ㄴ ㅈㅎㄱㄴ ㅇㄴ ㅂㅎㄹ ㄴㅇ

**Comment by hojak99** [comment]
참고로 제한시간은 12시까지입니다.

**Comment by kyle-seongwoo-jun** [comment]
그룹만 보면 동방신긴데 누구지 ... 존나 어렵네 진짜

**Comment by hojak99** [comment]
50분 남았습니다.

**Comment by kyle-seongwoo-jun** [comment]
ㅅㅂ 모르겠다 ... 인피니트H - 니가 없을 때 ???

**Comment by hojak99** [comment]
툴룠습니다.

**Comment by hojak99** [comment]
남자그룹이 아닙니다.

**Comment by kyle-seongwoo-jun** [comment]
그룹 이름이 들으면 알 정도로 유명합니까?

**Comment by hojak99** [comment]
정말 유명합니다. 아육대에도 나왔었습니다.

**Comment by hojak99** [comment]
8분남았습니다. 고기 냠냠. 맞췄으면 내가사는거입니다.

**Comment by kyle-seongwoo-jun** [comment]
씨스타19 있다 없으니까  !!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hojak99** [comment]
네 맞습니다.

**Comment by hojak99** [comment]
다음에 고기 사드리겠씁니다.
